<#
.SYNOPSIS
    Uninstall script for {{ app_name }} (Multi-strategy)

.DESCRIPTION
    This script attempts multiple uninstallation strategies:
    1. Standard uninstall via registry UninstallString
    2. Force removal if standard method fails
    
    Generated by Intune App Packager
    Application: {{ app_name }}
    Version: {{ app_version }}
    Publisher: {{ publisher }}

.NOTES
    Exit Codes:
    0 - Success
    1 - Generic failure
    1605 - Application not installed
#>

# Set strict mode
Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Logging configuration
$LogPath = "$env:ProgramData\IntuneAppPackager\Logs"
$LogFile = Join-Path $LogPath "{{ app_name }}_Uninstall_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

# Create log directory if it doesn't exist
if (!(Test-Path $LogPath)) {
    New-Item -Path $LogPath -ItemType Directory -Force | Out-Null
}

# Logging function
function Write-Log {
    param(
        [Parameter(Mandatory=$true)]
        [string]$Message,
        
        [Parameter(Mandatory=$false)]
        [ValidateSet('INFO', 'WARN', 'ERROR', 'DEBUG')]
        [string]$Level = 'INFO'
    )
    
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $logMessage = "[$timestamp] [$Level] $Message"
    
    Add-Content -Path $LogFile -Value $logMessage
    
    switch ($Level) {
        'ERROR' { Write-Host $logMessage -ForegroundColor Red }
        'WARN'  { Write-Host $logMessage -ForegroundColor Yellow }
        'INFO'  { Write-Host $logMessage -ForegroundColor Green }
        'DEBUG' { Write-Host $logMessage -ForegroundColor Gray }
    }
}

Write-Log "========================================" -Level INFO
Write-Log "Starting uninstallation of {{ app_name }} v{{ app_version }}" -Level INFO
Write-Log "========================================" -Level INFO

# Check if application is installed
Write-Log "Checking if application is installed..." -Level INFO
$isInstalled = $false

{% for rule in detection_rules %}
{% if rule.type == 'file' %}
if (Test-Path "{{ rule.path }}") {
    Write-Log "Found application file: {{ rule.path }}" -Level INFO
    $isInstalled = $true
}
{% elif rule.type == 'registry' %}
if (Test-Path "{{ rule.hive }}:\{{ rule.path }}") {
    Write-Log "Found registry key: {{ rule.hive }}:\{{ rule.path }}" -Level INFO
    $isInstalled = $true
}
{% endif %}
{% endfor %}

if (!$isInstalled) {
    Write-Log "Application {{ app_name }} is not installed" -Level WARN
    exit 1605  # Product not installed
}

# Strategy 1: Standard Uninstall
Write-Log "----------------------------------------" -Level INFO
Write-Log "Strategy 1: Attempting standard uninstall" -Level INFO

$standardUninstallSuccess = $false

# Search for uninstall string in registry
$uninstallKeys = @(
    "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*",
    "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*",
    "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*"
)

foreach ($keyPath in $uninstallKeys) {
    try {
        $apps = Get-ItemProperty $keyPath -ErrorAction SilentlyContinue | 
                Where-Object { $_.DisplayName -like "*{{ app_name }}*" }
        
        foreach ($app in $apps) {
            if ($app.UninstallString) {
                Write-Log "Found uninstall string: $($app.UninstallString)" -Level INFO
                
                # Parse uninstall string
                $uninstallCmd = $app.UninstallString
                
                # Add silent parameters based on installer type
                if ($uninstallCmd -like "*msiexec*") {
                    # MSI uninstall
                    $productCode = $uninstallCmd -replace '.*({.*}).*', '$1'
                    $uninstallArgs = "/x $productCode /qn /norestart"
                    $uninstallExe = "msiexec.exe"
                    Write-Log "MSI uninstall detected. Using: $uninstallExe $uninstallArgs" -Level INFO
                }
                elseif ($uninstallCmd -like "*.exe*") {
                    # EXE uninstaller
                    if ($uninstallCmd -match '"([^"]+)"') {
                        $uninstallExe = $matches[1]
                    } else {
                        $uninstallExe = ($uninstallCmd -split ' ')[0]
                    }
                    
                    # Try to add silent flags
                    $uninstallArgs = "/S /silent /VERYSILENT /quiet"
                    Write-Log "EXE uninstall detected. Using: $uninstallExe $uninstallArgs" -Level INFO
                }
                else {
                    Write-Log "Unknown uninstaller type: $uninstallCmd" -Level WARN
                    continue
                }
                
                # Execute uninstall
                try {
                    $process = Start-Process -FilePath $uninstallExe -ArgumentList $uninstallArgs -Wait -PassThru -NoNewWindow
                    $exitCode = $process.ExitCode
                    
                    Write-Log "Uninstall process exited with code: $exitCode" -Level INFO
                    
                    if ($exitCode -eq 0 -or $exitCode -eq 3010 -or $exitCode -eq 1605) {
                        Write-Log "Standard uninstall successful" -Level INFO
                        $standardUninstallSuccess = $true
                        break
                    }
                }
                catch {
                    Write-Log "Standard uninstall failed: $($_.Exception.Message)" -Level WARN
                }
            }
        }
    }
    catch {
        Write-Log "Error searching registry: $($_.Exception.Message)" -Level DEBUG
    }
    
    if ($standardUninstallSuccess) { break }
}

# Strategy 2: Force Removal (if standard failed)
if (!$standardUninstallSuccess) {
    Write-Log "----------------------------------------" -Level INFO
    Write-Log "Strategy 2: Force removal" -Level INFO
    Write-Log "Standard uninstall failed or not available. Attempting force removal..." -Level WARN
    
    # Kill running processes
    {% if processes_to_kill %}
    Write-Log "Terminating running processes..." -Level INFO
    $processesToKill = @({% for proc in processes_to_kill %}"{{ proc }}"{% if not loop.last %}, {% endif %}{% endfor %})
    
    foreach ($procName in $processesToKill) {
        try {
            $processes = Get-Process -Name ($procName -replace '\.exe$', '') -ErrorAction SilentlyContinue
            if ($processes) {
                foreach ($proc in $processes) {
                    Write-Log "Killing process: $($proc.Name) (PID: $($proc.Id))" -Level INFO
                    Stop-Process -Id $proc.Id -Force
                }
            }
        }
        catch {
            Write-Log "Could not kill process $procName : $($_.Exception.Message)" -Level DEBUG
        }
    }
    
    # Wait for processes to terminate
    Start-Sleep -Seconds 2
    {% endif %}
    
    # Remove installation folders
    {% if paths_to_remove %}
    Write-Log "Removing installation directories..." -Level INFO
    $pathsToRemove = @({% for path in paths_to_remove %}"{{ path }}"{% if not loop.last %}, {% endif %}{% endfor %})
    
    foreach ($path in $pathsToRemove) {
        if (Test-Path $path) {
            try {
                Write-Log "Removing: $path" -Level INFO
                Remove-Item -Path $path -Recurse -Force -ErrorAction Stop
                Write-Log "Successfully removed: $path" -Level INFO
            }
            catch {
                Write-Log "Failed to remove $path : $($_.Exception.Message)" -Level ERROR
            }
        }
        else {
            Write-Log "Path not found: $path" -Level DEBUG
        }
    }
    {% endif %}
    
    # Remove registry keys
    {% if registry_keys_to_remove %}
    Write-Log "Removing registry keys..." -Level INFO
    $registryKeys = @({% for key in registry_keys_to_remove %}"{{ key }}"{% if not loop.last %}, {% endif %}{% endfor %})
    
    foreach ($regKey in $registryKeys) {
        if (Test-Path $regKey) {
            try {
                Write-Log "Removing registry key: $regKey" -Level INFO
                Remove-Item -Path $regKey -Recurse -Force -ErrorAction Stop
                Write-Log "Successfully removed registry key: $regKey" -Level INFO
            }
            catch {
                Write-Log "Failed to remove registry key $regKey : $($_.Exception.Message)" -Level ERROR
            }
        }
        else {
            Write-Log "Registry key not found: $regKey" -Level DEBUG
        }
    }
    {% endif %}
    
    # Remove shortcuts
    {% if shortcuts %}
    Write-Log "Removing shortcuts..." -Level INFO
    {% for shortcut in shortcuts %}
    {% if 'Desktop' in shortcut.locations %}
    $desktopShortcut = Join-Path ([Environment]::GetFolderPath("Desktop")) "{{ shortcut.name }}.lnk"
    if (Test-Path $desktopShortcut) {
        Remove-Item $desktopShortcut -Force
        Write-Log "Removed desktop shortcut: $desktopShortcut" -Level INFO
    }
    {% endif %}
    
    {% if 'StartMenu' in shortcut.locations %}
    $startMenuShortcut = Join-Path ([Environment]::GetFolderPath("StartMenu")) "{{ shortcut.name }}.lnk"
    if (Test-Path $startMenuShortcut) {
        Remove-Item $startMenuShortcut -Force
        Write-Log "Removed start menu shortcut: $startMenuShortcut" -Level INFO
    }
    {% endif %}
    {% endfor %}
    {% endif %}
}

# Verify uninstallation
Write-Log "----------------------------------------" -Level INFO
Write-Log "Verifying uninstallation..." -Level INFO

$stillInstalled = $false

{% for rule in detection_rules %}
{% if rule.type == 'file' %}
if (Test-Path "{{ rule.path }}") {
    Write-Log "WARNING: File still exists: {{ rule.path }}" -Level WARN
    $stillInstalled = $true
}
{% elif rule.type == 'registry' %}
if (Test-Path "{{ rule.hive }}:\{{ rule.path }}") {
    Write-Log "WARNING: Registry key still exists: {{ rule.hive }}:\{{ rule.path }}" -Level WARN
    $stillInstalled = $true
}
{% endif %}
{% endfor %}

# Final summary
Write-Log "========================================" -Level INFO
Write-Log "Uninstallation Summary" -Level INFO
Write-Log "Application: {{ app_name }} v{{ app_version }}" -Level INFO

if ($stillInstalled) {
    Write-Log "Status: Partial uninstall - Some components remain" -Level WARN
    Write-Log "Manual cleanup may be required" -Level WARN
    exit 1
}
else {
    Write-Log "Status: Successfully uninstalled" -Level INFO
    Write-Log "Application has been completely removed from the system" -Level INFO
}

Write-Log "Log file: $LogFile" -Level INFO
Write-Log "========================================" -Level INFO

exit 0
