<#
.SYNOPSIS
    Detection script for {{ app_name }}

.DESCRIPTION
    Comprehensive detection script that checks multiple indicators:
    - File existence and version
    - Registry keys and values  
    - Process state (optional)
    
    Generated by Intune App Packager
    Application: {{ app_name }}
    Version: {{ app_version }}
    Publisher: {{ publisher }}

.NOTES
    Exit Codes:
    0 - Application detected (installed)
    1 - Application not detected (not installed)
    
    Intune interprets exit code 0 as "detected" and any non-zero as "not detected"
#>

# Set strict mode
Set-StrictMode -Version Latest
$ErrorActionPreference = "SilentlyContinue"

# Detection results
$detectionResults = @()
$allChecksPassed = $true

{% for rule in detection_rules %}
{% if rule.type == 'file' %}
# File Check: {{ rule.path }}
$filePath = "{{ rule.path }}"
if (Test-Path $filePath) {
    {% if rule.check_version %}
    # Version check required
    $fileVersion = (Get-Item $filePath).VersionInfo.FileVersion
    $requiredVersion = "{{ rule.min_version }}"
    
    if ($fileVersion) {
        try {
            $currentVer = [Version]$fileVersion
            $minVer = [Version]$requiredVersion
            
            if ($currentVer -ge $minVer) {
                $detectionResults += "✓ File found: $filePath (version $fileVersion >= $requiredVersion)"
            }
            else {
                $detectionResults += "✗ File found but version too old: $filePath (version $fileVersion < $requiredVersion)"
                $allChecksPassed = $false
            }
        }
        catch {
            $detectionResults += "✗ File found but version check failed: $filePath"
            $allChecksPassed = $false
        }
    }
    else {
        $detectionResults += "✗ File found but no version information: $filePath"
        $allChecksPassed = $false
    }
    {% else %}
    $detectionResults += "✓ File found: $filePath"
    {% endif %}
}
else {
    $detectionResults += "✗ File not found: $filePath"
    $allChecksPassed = $false
}

{% elif rule.type == 'registry' %}
# Registry Check: {{ rule.hive }}:\{{ rule.path }}
$regPath = "{{ rule.hive }}:\{{ rule.path }}"
if (Test-Path $regPath) {
    {% if rule.value %}
    # Check specific registry value
    try {
        $regValue = Get-ItemProperty -Path $regPath -Name "{{ rule.value }}" -ErrorAction SilentlyContinue
        if ($regValue) {
            $actualValue = $regValue."{{ rule.value }}"
            {% if rule.operator == 'Exists' %}
            $detectionResults += "✓ Registry value exists: $regPath\{{ rule.value }} = $actualValue"
            {% elif rule.operator == 'Equals' %}
            if ($actualValue -eq "{{ rule.expected }}") {
                $detectionResults += "✓ Registry value matches: $regPath\{{ rule.value }} = $actualValue"
            }
            else {
                $detectionResults += "✗ Registry value mismatch: $regPath\{{ rule.value }} = $actualValue (expected: {{ rule.expected }})"
                $allChecksPassed = $false
            }
            {% elif rule.operator == 'GreaterOrEqual' %}
            try {
                $currentVer = [Version]$actualValue
                $minVer = [Version]"{{ rule.expected }}"
                if ($currentVer -ge $minVer) {
                    $detectionResults += "✓ Registry version OK: $regPath\{{ rule.value }} = $actualValue >= {{ rule.expected }}"
                }
                else {
                    $detectionResults += "✗ Registry version too old: $regPath\{{ rule.value }} = $actualValue < {{ rule.expected }}"
                    $allChecksPassed = $false
                }
            }
            catch {
                $detectionResults += "✗ Registry version check failed: $regPath\{{ rule.value }}"
                $allChecksPassed = $false
            }
            {% endif %}
        }
        else {
            $detectionResults += "✗ Registry value not found: $regPath\{{ rule.value }}"
            $allChecksPassed = $false
        }
    }
    catch {
        $detectionResults += "✗ Error reading registry value: $regPath\{{ rule.value }}"
        $allChecksPassed = $false
    }
    {% else %}
    # Just check key existence
    $detectionResults += "✓ Registry key exists: $regPath"
    {% endif %}
}
else {
    $detectionResults += "✗ Registry key not found: $regPath"
    $allChecksPassed = $false
}

{% elif rule.type == 'process' %}
# Process Check: {{ rule.process_name }}
$processName = "{{ rule.process_name }}" -replace '\.exe$', ''
$process = Get-Process -Name $processName -ErrorAction SilentlyContinue
if ($process) {
    $detectionResults += "✓ Process running: {{ rule.process_name }}"
}
else {
    {% if rule.required %}
    $detectionResults += "✗ Process not running: {{ rule.process_name }}"
    $allChecksPassed = $false
    {% else %}
    $detectionResults += "ℹ Process not running (optional): {{ rule.process_name }}"
    {% endif %}
}

{% endif %}
{% endfor %}

{% if custom_detection_script %}
# Custom Detection Logic
try {
    {{ custom_detection_script | indent(4) }}
    
    if ($?) {
        $detectionResults += "✓ Custom detection check passed"
    }
    else {
        $detectionResults += "✗ Custom detection check failed"
        $allChecksPassed = $false
    }
}
catch {
    $detectionResults += "✗ Custom detection error: $($_.Exception.Message)"
    $allChecksPassed = $false
}
{% endif %}

# Output detection results (for logging/debugging)
# Note: Intune only cares about exit code, but this output can help troubleshooting
Write-Host "========================================"
Write-Host "Detection Results for {{ app_name }} v{{ app_version }}"
Write-Host "========================================"
foreach ($result in $detectionResults) {
    Write-Host $result
}
Write-Host "========================================"

# Return appropriate exit code
if ($allChecksPassed) {
    Write-Host "DETECTED: Application is installed"
    exit 0  # Application detected
}
else {
    Write-Host "NOT DETECTED: Application is not installed or requirements not met"
    exit 1  # Application not detected
}
